<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\js\ClaimsClient.js" />
    <Content Remove="wwwroot\js\JwtAuthSchemeClient.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\js\ClaimsClient.js" />
    <None Include="wwwroot\js\JwtAuthSchemeClient.js" />
    <None Include="wwwroot\js\CustomAuthSchemeClient.js" />
  </ItemGroup>

</Project>
