services:
  oidc-server-mock:
    image: ghcr.io/soluto/oidc-server-mock
    ports:
      - "4012:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      SERVER_OPTIONS_INLINE: |
        {
          "AccessTokenJwtType": "JWT",
          "Discovery": {
            "ShowKeySet": true
          },
          "Authentication": {
            "CookieSameSiteMode": "Lax",
            "CheckSessionCookieSameSiteMode": "Lax"
          }
        }
      ACCOUNT_OPTIONS_INLINE: |
        {
          "AutomaticRedirectAfterSignOut": true
        }
      API_SCOPES_INLINE: |
        [
          {
            "Name": "workshop_api"
          },
        ]
      API_RESOURCES_INLINE: |
        [
          {
            "Name": "workshop",
            "Scopes": ["workshop_api"],
            "UserClaims": [
              "title",
              "given_name",
              "aud",
              "family_name",
              "email",
              "name",
              "preferred_username"
            ]
          }
        ]
      USERS_CONFIGURATION_PATH: /tmp/config/users-config.json
      CLIENTS_CONFIGURATION_PATH: /tmp/config/clients-config.json
      IDENTITY_RESOURCES_INLINE: | 
        [ { "Name": "workshop", "ClaimTypes": ["craft", "role"] } ]
    volumes:
      - .:/tmp/config:ro

volumes:
  azurite:
  seqdata:

networks:
  proxy_net:
    driver: bridge
  default:
    name: auth-net